/**
 * WCAG contrast gate for the design tokens.
 *
 *   node scripts/contrast.mjs     check both palette variants, print a table,
 *                                 write design/contrast.md, exit 1 on any failure
 *
 * The pair list and math live in scripts/contrastCore.mjs so the vitest suite and the
 * /styleguide page run the exact same checks.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { checkVariant, parseVariants, resolveToken, scoreVariant, SERIES, simulate } from './contrastCore.mjs';

const ROOT = resolve(import.meta.dirname, '..');
const css = readFileSync(join(ROOT, 'src/styles/tokens.css'), 'utf8');
const variants = parseVariants(css);
const NAMES = { a: 'A, Cream and Coral (default)', b: 'B, Ember' };

const f2 = (n) => n.toFixed(2);
let failures = 0;
const md = [
  '# Contrast report',
  '',
  'Generated by `node scripts/contrast.mjs` from `src/styles/tokens.css`. Do not edit by hand.',
  '',
  'Thresholds: 4.5:1 for text (WCAG 1.4.3), 3:1 for focus rings, control borders, progress fills, and chart series (WCAG 1.4.11).',
  '',
];

for (const [key, map] of Object.entries(variants)) {
  const rows = checkVariant(map);
  const bad = rows.filter((r) => !r.pass);
  failures += bad.length;

  console.log(`\nVariant ${NAMES[key]}`);
  console.log(`${'foreground'.padEnd(14)} ${'background'.padEnd(14)} ${'ratio'.padStart(6)}  min  result`);
  for (const r of rows)
    console.log(
      `${r.fg.padEnd(14)} ${r.bg.padEnd(14)} ${f2(r.ratio).padStart(6)}  ${String(r.min).padEnd(3)}  ${r.pass ? 'pass' : 'FAIL'}`,
    );

  const s = scoreVariant(map);
  md.push(`## Variant ${NAMES[key]}`, '');
  md.push(`${rows.length - bad.length} of ${rows.length} pairs pass.`, '');
  md.push('| Foreground | Background | Colors | Ratio | Min | Result | Use |', '|---|---|---|---:|---:|---|---|');
  for (const r of rows)
    md.push(
      `| \`${r.fg}\` | \`${r.bg}\` | ${r.fgHex} on ${r.bgHex} | ${f2(r.ratio)} | ${r.min} | ${r.pass ? 'pass' : '**FAIL**'} | ${r.use} |`,
    );
  md.push('', '### Separation', '');
  md.push(
    `- Smallest text margin over its threshold: ${f2(s.minTextMargin)}x (lowest text ratio ${f2(s.minTextRatio)}:1).`,
    `- Body text (\`--ink\` on \`--bg\`): ${f2(s.bodyRatio)}:1.`,
    `- Chart series, smallest pairwise delta E (CIE76): normal ${f2(s.series.normal)}, deuteranopia ${f2(s.series.deuteranopia)}, protanopia ${f2(s.series.protanopia)}.`,
    `- \`--accent-ink\` vs \`--danger\` delta E: normal ${f2(s.accentDanger.normal)}, deuteranopia ${f2(s.accentDanger.deuteranopia)}.`,
    `- Page chroma (\`--bg\`, Lab): ${f2(s.bgChroma)}.`,
    '',
    '| Series | Color | Deuteranopia | Protanopia |',
    '|---|---|---|---|',
    ...SERIES.map((t) => {
      const h = resolveToken(map, t);
      return `| \`${t}\` | ${h} | ${simulate(h, 'deuteranopia')} | ${simulate(h, 'protanopia')} |`;
    }),
    '',
  );
}

mkdirSync(join(ROOT, 'design'), { recursive: true });
writeFileSync(join(ROOT, 'design/contrast.md'), md.join('\n'));
console.log(failures ? `\n${failures} pair(s) FAIL.` : '\nAll pairs pass in both variants. Wrote design/contrast.md.');
process.exit(failures ? 1 : 0);
